services:
  frontend:
    build: 
      context: ./front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - path: ./front/.env
        required: true
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app/back
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - path: ./back/.env
        required: true